AWSTemplateFormatVersion: 2010-09-09
Description: 'S3 Static file hosting'

Resources:

# creating an s3 bucket

  Mys3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'static-s3-bucket-99'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false


#Bucket Policy for MyS3Bucket, allowing public access

  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref Mys3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement: 
          - Sid: 'PublicReadGetObject' 
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${Mys3Bucket}/*'


              
